### ISSUE TITLE
Spams main directory with folders?

### ISSUE THREAD

**Issue by 13en91** [AndreasElia/popapi#3]
on running php artisan scrape:funko this seems to just recreate the dirs in the apps main directory and nothing else =/

**Comment by andreaselia** [comment]
@13en91 thanks, I'll have a look into this as soon as I get home this evening and update the issue afterwards.

**Comment by andreaselia** [comment]
@13en91 apologies for the late reply. I had a look into this and the script for sure seems to be creating directories for each collection when scraping. I'll fix this tonight and push a commit.

**Comment by 13en91** [comment]
Thank you Andreas!

**Comment by andreaselia** [comment]
@13en91 I have pushed a fix for this issue 😄
