### ISSUE TITLE
Collections database migration down function 

### ISSUE THREAD

**Issue by 13ens** [AndreasElia/popapi#4]
Collections and Results is using the create function instead of dropIfExists which means if you go to php artisan db:refresh it fails

public function down()
    {
        Schema::create('collections');
    }

**Comment by andreaselia** [comment]
If you'd like to submit a PR with a fix that would be greatly appreciated. This isn't actively maintained anymore and am currently too busy to setup this project again to fix any issue(s).

**Comment by andreaselia** [comment]
This has been fixed. The project will be re-written whenever I get the time. I have created a separate branch for the said rewrite.
